New element in section 2 on gathering of data and preparation of datasets for training and evaluation
LabeliaLabs/referentiel-evaluation-dsrc pull request #173
Opened 2021-11-29 16:42 UTC by bowni

…s for training and evaluation

2021-11-29 16:46 UTC, bowni commented
Arf, this should have been a draft PR for now - still have to do the English version

2021-12-01 16:22 UTC, bowni commented
Hey @ClementMayer @meuce @celinejacques @SaboniAmine @RomainGoussault could one of you check and validate this PR to finalize the 2021H2 release candidate?
We'll circulate it to the whole communities later today or tomorrow at a maximum!
Thanks!

2021-12-01 16:34 UTC, SaboniAmine approved these changes

2021-12-01 16:35 UTC, ClementMayer approved these changes

2021-12-01 16:43 UTC, SaboniAmine requested changes
Typo & alternative phrasing suggestions

2021-12-01 16:43 UTC, SaboniAmine commented on assessment_framework_eng.md
> +Obtaining and preparing the dataasets is a core acitivity in every data science project. Each data point can have an impact on the learning, and it is thus crucial to define and implement a conscious
Obtaining and preparing _datasets_

2021-12-01 16:43 UTC, SaboniAmine commented on assessment_framework_eng.md
> +
alt: for _extensive_ exploratory

2021-12-01 16:43 UTC, SaboniAmine commented on assessment_framework_eng.md
> +- [ ] 2.4.b We pay particular attention to the identification of protected attributes and their possible proxies (e.g. studying one by one the variables used as model inputs to identify the correlati
alt : We pay _special_ attention

2021-12-02 09:58 UTC, bowni commented on assessment_framework_eng.md
> +- [ ] 2.4.b We pay particular attention to the identification of protected attributes and their possible proxies (e.g. studying one by one the variables used as model inputs to identify the correlati
Done

2021-12-02 09:58 UTC, bowni commented on assessment_framework_eng.md
> +
Done

2021-12-02 09:58 UTC, bowni commented on assessment_framework_eng.md
> +Obtaining and preparing the dataasets is a core acitivity in every data science project. Each data point can have an impact on the learning, and it is thus crucial to define and implement a conscious
Done

2021-12-02 09:58 UTC, bowni commented
Thanks @SaboniAmine , changes done, I let you finalize your review and approve!

2021-12-02 10:25 UTC, ClementMayer approved these changes

2021-12-02 10:30 UTC, SaboniAmine approved these changes

2021-12-02 10:41 UTC, merged